apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-comm-rp
  namespace: spark-jobs
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: thinhdv1305/spark-pbh:17.0
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/spark/work-dir/scripts/loadCommRp.py
  sparkVersion: "3.5.0"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreLimit: "1000m"
    memory: "4096m"
    labels:
      version: 3.0.0
    serviceAccount: spark
    envVars:
      SQL_QUERY: ""
  executor:
    instances: 1
    coreRequest: "1000m"
    coreLimit: "1000m"
    memory: "4096m"
    labels:
      version: 3.0.0
  deps:
    jars:
      - https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar
      - https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar
      - https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.28/mysql-connector-java-8.0.28.jar
      - https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-common/3.3.4/hadoop-common-3.3.4.jar
      - https://repo1.maven.org/maven2/com/oracle/database/jdbc/ojdbc8/23.2.0.0/ojdbc8-23.2.0.0.jar
